### ISSUE TITLE
an error occurred in installing CWGCNA

### ISSUE THREAD

**Issue by cwu2011** [yuabrahamliu/CWGCNA#10]
I tried to install CWGCNA with Rstudio (2024.04.2 build 764).
An error occurred in downloading the package from github. The message is as below:
> install_github("yuabrahamliu/CWGCNA")
Using github PAT from envvar GITHUB_PAT. Use `gitcreds::gitcreds_set()` and unset GITHUB_PAT in .Renviron (or elsewhere) if you want to use the more secure git credential store instead.
Downloading GitHub repo yuabrahamliu/CWGCNA@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/yuabrahamliu/CWGCNA/tarball/HEAD' failed

what should I do with my Rstudio or github setting ? Thank you!

**Comment by cwu2011** [comment]
The version of R in my computer is 4.4.0.

**Comment by yuabrahamliu** [comment]
From your message, you have a `PAT` (personal access token) set with your envvar `GITHUB_PAT`, which caused the installation error.

You can check it via `Sys.getenv("GITHUB_PAT")`, and record it in case you need it in the future.

Then, unset it via `Sys.unsetenv("GITHUB_PAT")`, and you should be able to install the package.

**Comment by cwu2011** [comment]
i found there maybe some problems with my network connection.
it failed to install some dependency packages from bioconductor.
i will try it some more times.
thanks a lot！
