### ISSUE TITLE
An error in the use of CWGCNA package

### ISSUE THREAD

**Issue by ruikangHAN** [yuabrahamliu/CWGCNA#11]
Hi, thank you for your package. But I was trapped by an error when using the CWGCNA package in RStudio. The WGCNA part ran smoothly and i could also identify the differential modules between my groups.

However, when i was doing the mediation analysis, I got an error saying Error in 1:(ncol(resline) - 3) : 参数长度为零. So I looked up the variable, resline, in your source code ( from github, R ), but I could only see a variable named reslines, instead of resline.

I have completely no idea where this mistake is coming from, and I would appreciate it a lot if you are willing to help. Many thanks in advance !

                                                                                                                      
the code i used is posted below.

net<- diffwgcna(
  dat=data,
  pddat=sample_info,
  responsevarname = 'Group',
  responselevels = NULL,
  confoundings = NULL,
  topvaricancetype = "mad",
  topvaricance = 10000,
 
  balanceadj = FALSE,
  #samplingmethod = "updn",
  #nround = 10,
  #seed = 2022,
  #k = 5,
  threads = 6,
  #method = "Cauchy",
 
  sftpowers = 9,
  #powers = seq(1, 20, 1),
  #rsqcutline = 0.8,
 
  minclustersize = 30,
  mergecutheight = 0.25,
  maxblocksize = 30000,
 
  removereg = NULL,
  featuretype = "gene",
 
  topoenrichment = FALSE,
  #shufflenum = 1000,
 
  mediation = TRUE,
  topn = 4,
  #platform = 450,
  #ignorestrand = TRUE,
  #tssradius = 1500,
 
  plot = TRUE,
  titleprefix = 'cWGCNA-test-Diseased/WT',
  isbetaval = FALSE,
  diffcutoff = 0,
  pvalcutoff = 0.05,
  pvalcolname = "adj.P.Val",
  absxcutoff = 0,
 
  face = "bold",
  labelnum = 10,
  titlesize = 15,
  textsize = 13,
  annotextsize = 4,
  savetom = TRUE
)

**Comment by ruikangHAN** [comment]
update:
I changed the parameter 'threads=6' to ' threads =1', but it still wouldn't work.

**Comment by yuabrahamliu** [comment]
> Hi, thank you for your package. But I was trapped by an error when using the CWGCNA package in RStudio. The WGCNA part ran smoothly and i could also identify the differential modules between my groups.
> 
> However, when i was doing the mediation analysis, I got an error saying Error in 1:(ncol(resline) - 3) : 参数长度为零. So I looked up the variable, resline, in your source code ( from github, R ), but I could only see a variable named reslines, instead of resline.
> 
> I have completely no idea where this mistake is coming from, and I would appreciate it a lot if you are willing to help. Many thanks in advance !
> 
> the code i used is posted below.
> 
> net<- diffwgcna( dat=data, pddat=sample_info, responsevarname = 'Group', responselevels = NULL, confoundings = NULL, topvaricancetype = "mad", topvaricance = 10000,
> 
> balanceadj = FALSE, #samplingmethod = "updn", #nround = 10, #seed = 2022, #k = 5, threads = 6, #method = "Cauchy",
> 
> sftpowers = 9, #powers = seq(1, 20, 1), #rsqcutline = 0.8,
> 
> minclustersize = 30, mergecutheight = 0.25, maxblocksize = 30000,
> 
> removereg = NULL, featuretype = "gene",
> 
> topoenrichment = FALSE, #shufflenum = 1000,
> 
> mediation = TRUE, topn = 4, #platform = 450, #ignorestrand = TRUE, #tssradius = 1500,
> 
> plot = TRUE, titleprefix = 'cWGCNA-test-Diseased/WT', isbetaval = FALSE, diffcutoff = 0, pvalcutoff = 0.05, pvalcolname = "adj.P.Val", absxcutoff = 0,
> 
> face = "bold", labelnum = 10, titlesize = 15, textsize = 13, annotextsize = 4, savetom = TRUE )

This error was not reported before. I also cannot find any problem from your current information. 

So, please share me an example dataset with this error and I will look into it. Thank you.

**Comment by ruikangHAN** [comment]
Hi, I attached my dataset and sample info below. Thank you for your quick response.
[input_data.txt](https://github.com/user-attachments/files/17129327/input_data.txt)
[sample_info.txt](https://github.com/user-attachments/files/17129329/sample_info.txt)

**Comment by ruikangHAN** [comment]
> > Hi, thank you for your package. But I was trapped by an error when using the CWGCNA package in RStudio. The WGCNA part ran smoothly and i could also identify the differential modules between my groups.
> > However, when i was doing the mediation analysis, I got an error saying Error in 1:(ncol(resline) - 3) : 参数长度为零. So I looked up the variable, resline, in your source code ( from github, R ), but I could only see a variable named reslines, instead of resline.
> > I have completely no idea where this mistake is coming from, and I would appreciate it a lot if you are willing to help. Many thanks in advance !
> > the code i used is posted below.
> > net<- diffwgcna( dat=data, pddat=sample_info, responsevarname = 'Group', responselevels = NULL, confoundings = NULL, topvaricancetype = "mad", topvaricance = 10000,
> > balanceadj = FALSE, #samplingmethod = "updn", #nround = 10, #seed = 2022, #k = 5, threads = 6, #method = "Cauchy",
> > sftpowers = 9, #powers = seq(1, 20, 1), #rsqcutline = 0.8,
> > minclustersize = 30, mergecutheight = 0.25, maxblocksize = 30000,
> > removereg = NULL, featuretype = "gene",
> > topoenrichment = FALSE, #shufflenum = 1000,
> > mediation = TRUE, topn = 4, #platform = 450, #ignorestrand = TRUE, #tssradius = 1500,
> > plot = TRUE, titleprefix = 'cWGCNA-test-Diseased/WT', isbetaval = FALSE, diffcutoff = 0, pvalcutoff = 0.05, pvalcolname = "adj.P.Val", absxcutoff = 0,
> > face = "bold", labelnum = 10, titlesize = 15, textsize = 13, annotextsize = 4, savetom = TRUE )
> 
> This error was not reported before. I also cannot find any problem from your current information.
> 
> So, please share me an example dataset with this error and I will look into it. Thank you.

Hi, I attached my dataset and sample info below. Thank you for your quick response.
[input_data.txt](https://github.com/user-attachments/files/17129363/input_data.txt)
[sample_info.txt](https://github.com/user-attachments/files/17129370/sample_info.txt)

**Comment by ruikangHAN** [comment]
update: it seems that I didn't have enough columns for resline. 
The error comes from the code:
resline$source <- sourcename
resline$target <- targetname

resline <- resline[,c('source', 'target', 'mediator', 
                      colnames(resline)[1:(ncol(resline) - 3)])]
in emethyl_mediation part.

**Comment by yuabrahamliu** [comment]
> > > Hi, thank you for your package. But I was trapped by an error when using the CWGCNA package in RStudio. The WGCNA part ran smoothly and i could also identify the differential modules between my groups.
> > > However, when i was doing the mediation analysis, I got an error saying Error in 1:(ncol(resline) - 3) : 参数长度为零. So I looked up the variable, resline, in your source code ( from github, R ), but I could only see a variable named reslines, instead of resline.
> > > I have completely no idea where this mistake is coming from, and I would appreciate it a lot if you are willing to help. Many thanks in advance !
> > > the code i used is posted below.
> > > net<- diffwgcna( dat=data, pddat=sample_info, responsevarname = 'Group', responselevels = NULL, confoundings = NULL, topvaricancetype = "mad", topvaricance = 10000,
> > > balanceadj = FALSE, #samplingmethod = "updn", #nround = 10, #seed = 2022, #k = 5, threads = 6, #method = "Cauchy",
> > > sftpowers = 9, #powers = seq(1, 20, 1), #rsqcutline = 0.8,
> > > minclustersize = 30, mergecutheight = 0.25, maxblocksize = 30000,
> > > removereg = NULL, featuretype = "gene",
> > > topoenrichment = FALSE, #shufflenum = 1000,
> > > mediation = TRUE, topn = 4, #platform = 450, #ignorestrand = TRUE, #tssradius = 1500,
> > > plot = TRUE, titleprefix = 'cWGCNA-test-Diseased/WT', isbetaval = FALSE, diffcutoff = 0, pvalcutoff = 0.05, pvalcolname = "adj.P.Val", absxcutoff = 0,
> > > face = "bold", labelnum = 10, titlesize = 15, textsize = 13, annotextsize = 4, savetom = TRUE )
> > 
> > 
> > This error was not reported before. I also cannot find any problem from your current information.
> > So, please share me an example dataset with this error and I will look into it. Thank you.
> 
> Hi, I attached my dataset and sample info below. Thank you for your quick response. [input_data.txt](https://github.com/user-attachments/files/17129363/input_data.txt) [sample_info.txt](https://github.com/user-attachments/files/17129370/sample_info.txt)

Sorry for this late reply. 

I have updated the code, and you can re-install the package to run on your data. There should be no bug this time.

In addition, your data's results seem weird, which may be because you didn't provide confounding factors for such a disease dataset. So, I suggest you find and provide confounding factors. Thank you.

**Comment by ruikangHAN** [comment]
Notice: this is an auto reply.Your email was successfully delivered.Thanks for contacting and I will reply as soon as possible.
