### ISSUE TITLE
Is it possible to map the results of completed WGCNA analyses?

### ISSUE THREAD

**Issue by AcetylCoALab** [yuabrahamliu/CWGCNA#5]
During this software run, diffwgcna completes the WGCNA analysis and the mediator analysis together. Is it possible to do this in a step-by-step manner? If I have a result where WGCNA has already been calculated, will I be able to carry out the mediator analysis without any problems?

**Comment by yuabrahamliu** [comment]
The current version couples the mediation analysis and WGCNA together, so you must run WGCNA within the `diffwgcna` function.
