### ISSUE TITLE
Error in { : task 1 failed - "replacement has 1 row, data has 48"

### ISSUE THREAD

**Issue by lgbTime** [yuabrahamliu/CWGCNA#6]
this is y pds data
> head(pds2)
  sampleid     IS.04  WMW0159 WMW0023.011  WMW0016 KMW0413  NMW0072 KMW0616.152
1    A.Y.1 1084977.5 4103.255    171.2793 18566.60 1739352 80968.74    5726.725
2    A.Y.2 1089711.2 2988.956    171.2793 19248.12 1414009 45453.83   12513.269
3    A.Y.3 1105555.9 3492.240   1935.8474 18178.46 1294257 40689.64    5901.081
4    B.Y.1 1063279.8 2834.687   1710.5971 11270.84 1324526 47203.51    5687.213
5    B.Y.2 1017327.6 3284.444    171.2793 19028.21 1331204 79408.05   10904.174
6    B.Y.3  807621.3 6612.773    171.2793 22428.24 1537412 74619.33   10067.128
   KMW0418 XMW0980.143
1 30174.77    2132.938
2 39776.39    2492.863
3 31653.37    7887.309
4 28957.24    1129.662
5 38442.77    1518.866
6 36197.18    1249.780

this is my top10k::
> head(top10k$varicanceres, 3)
                   SD
LOC111908249 4125.483
LOC111888054 3158.018
LOC111917913 3139.616

> head(top10k$betas[1:3,1:3])
              A.Y.1  A.Y.2  A.Y.3
LOC122194388 135.06 155.74 149.98
LOC111905260  52.75  67.06 100.71
LOC111905261   1.59   1.92   1.11

I have run ::
> anovares <- featuresampling(betas = top10k$betas,  # 使用 betas
                            pddat = pds2,   # 性状数据
                            anova = TRUE,  # 执行 ANOVA
                            plotannovares = TRUE, # 绘制数据的ANOVA结果
                            featuretype = "probe",  
                            plottitlesuffix = "placenta", # 显示在图表标题中的字符
                            titlesize = 18, 
                            textsize = 16, 
                            threads = 6)
Error in { : task 1 failed - "replacement has 1 row, data has 48"

**Comment by yuabrahamliu** [comment]
Please take a look at the solution for this similar issue. 

https://github.com/yuabrahamliu/CWGCNA/issues/2#issuecomment-2113367521
