### ISSUE TITLE
Description in README

### ISSUE THREAD

**Issue by SudhirGhandikota** [yuabrahamliu/CWGCNA#9]
Hello,

There seems to be some discrepancy in the text description in the readme file and the manuscript concerning the mediation analysis results. Specifically, in the readme file you seem to describe the blue dots to be causal in the reverse direction, which should be 'phenotype->module feature->module' right? I can also see this in the 'source' and 'target' columns in the 'mediationres' slot of the result object. But, in the readme file, you seem to indicate that it is the other way around (ME3->ME3 gene->preeclampsia). The same goes for the red dots as well. Can you confirm which one is right, the directions specified in the readme file text or the manuscript+result object?

**Comment by yuabrahamliu** [comment]
Thank you for your question. 

Please follow the formal publication. The README file on GitHub has been updated to avoid confusion.

**Comment by SudhirGhandikota** [comment]
Thank you for the confirmation!

**Comment by SudhirGhandikota** [comment]
Hello Dr. Liu,

I had a query about the mediation analysis part and was hoping to get your clarification. For some input features, the propensity scores come out as ‘NA’. Can you comment on these NA values and give your advice on how to interpret them? Can we still consider these features to be significant?
 
Hoping to hear back from you.

**Comment by yuabrahamliu** [comment]
Sorry for this late reply.

I think you mean the "Prop" column in the result. It represents the mediation proportion explained by the feature, rather than the propensity score. 

If a feature has an insignficant mediantion effect, this column will be labeled as NA, so you don't need to consider this feature any longer.

**Comment by SudhirGhandikota** [comment]
Understood Dr. Liu. Thanks for your response!
